"""empty message

Revision ID: ef0b6e646f48
Revises: 
Create Date: 2022-11-26 01:39:26.248040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0b6e646f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_of_task', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('input_path', sa.String(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_info')
    # ### end Alembic commands ###
